# ===========================
# Namespace
# ===========================
apiVersion: v1
kind: Namespace
metadata:
  name: quizbuilder

---
# ===========================
# Backend Deployment
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend
  namespace: quizbuilder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-backend
  template:
    metadata:
      labels:
        app: quiz-backend
    spec:
      containers:
        - name: quiz-backend
          image: your-dockerhub-username/quiz-backend:latest   # ⬅ replace with your image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend
  namespace: quizbuilder
spec:
  selector:
    app: quiz-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
# ===========================
# Frontend Deployment
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
  namespace: quizbuilder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      containers:
        - name: quiz-frontend
          image: your-dockerhub-username/quiz-frontend:latest   # ⬅ replace with your image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend
  namespace: quizbuilder
spec:
  selector:
    app: quiz-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# ===========================
# Ingress (Frontend + API)
# ===========================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quizbuilder-ingress
  namespace: quizbuilder
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: quizbuilder.local    # ⬅ replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quiz-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: quiz-backend
                port:
                  number: 8080
